// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Partsunlimited.CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIPartsUnlimitedStoreAWindow UIPartsUnlimitedStoreAWindow
        {
            get
            {
                if ((this.mUIPartsUnlimitedStoreAWindow == null))
                {
                    this.mUIPartsUnlimitedStoreAWindow = new UIPartsUnlimitedStoreAWindow();
                }
                return this.mUIPartsUnlimitedStoreAWindow;
            }
        }
        
        public UICalculatedtax0Window UICalculatedtax0Window
        {
            get
            {
                if ((this.mUICalculatedtax0Window == null))
                {
                    this.mUICalculatedtax0Window = new UICalculatedtax0Window();
                }
                return this.mUICalculatedtax0Window;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPartsUnlimitedStoreAWindow mUIPartsUnlimitedStoreAWindow;
        
        private UICalculatedtax0Window mUICalculatedtax0Window;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPartsUnlimitedStoreAWindow : WinWindow
    {
        
        public UIPartsUnlimitedStoreAWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "PartsUnlimited Store Application";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("PartsUnlimited Store Application");
            #endregion
        }
        
        #region Properties
        public UIMenuStrip1MenuBar UIMenuStrip1MenuBar
        {
            get
            {
                if ((this.mUIMenuStrip1MenuBar == null))
                {
                    this.mUIMenuStrip1MenuBar = new UIMenuStrip1MenuBar(this);
                }
                return this.mUIMenuStrip1MenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuStrip1MenuBar mUIMenuStrip1MenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMenuStrip1MenuBar : WinMenuBar
    {
        
        public UIMenuStrip1MenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "MenuBar";
            this.WindowTitles.Add("PartsUnlimited Store Application");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIReportsToolstripMenuMenuItem
        {
            get
            {
                if ((this.mUIReportsToolstripMenuMenuItem == null))
                {
                    this.mUIReportsToolstripMenuMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIReportsToolstripMenuMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "reportsToolstripMenuItem";
                    this.mUIReportsToolstripMenuMenuItem.WindowTitles.Add("PartsUnlimited Store Application");
                    #endregion
                }
                return this.mUIReportsToolstripMenuMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIReportsToolstripMenuMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICalculatedtax0Window : WinWindow
    {
        
        public UICalculatedtax0Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Calculated tax: 0";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Static";
            this.WindowTitles.Add("Calculated tax: 0");
            #endregion
        }
        
        #region Properties
        public WinText UICalculatedtax0Text
        {
            get
            {
                if ((this.mUICalculatedtax0Text == null))
                {
                    this.mUICalculatedtax0Text = new WinText(this);
                    #region Search Criteria
                    this.mUICalculatedtax0Text.SearchProperties[WinText.PropertyNames.Name] = "Calculated tax: 0";
                    this.mUICalculatedtax0Text.WindowTitles.Add("Calculated tax: 0");
                    #endregion
                }
                return this.mUICalculatedtax0Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUICalculatedtax0Text;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
